# Generated by Django 2.0.6 on 2018-10-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
    ]
