# Generated by Django 2.0.6 on 2018-06-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='face',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='name',
            new_name='nome',
        ),
    ]
