# Generated by Django 2.0.6 on 2018-06-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180623_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_aula', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
