# Generated by Django 2.0.6 on 2018-06-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180621_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_presente',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
