# Generated by Django 2.0.6 on 2018-10-03 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ra', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='')),
                ('is_presente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_aula', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('alunos', models.ManyToManyField(to='core.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Momento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField(auto_now=True)),
                ('alunos_presentes', models.CharField(max_length=30)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aula')),
            ],
        ),
    ]
