# Generated by Django 2.0.6 on 2018-10-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='data_final',
            field=models.DateTimeField(default='1990-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aula',
            name='data_inicio',
            field=models.DateTimeField(default='1990-01-01'),
            preserve_default=False,
        ),
    ]
