# Generated by Django 2.0.6 on 2018-10-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181003_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momento',
            name='alunos_presentes',
        ),
        migrations.AddField(
            model_name='momento',
            name='alunos_presentes',
            field=models.ManyToManyField(related_name='alunos', to='core.Aluno'),
        ),
    ]
